version: '3.8'
services:
  database:
    image: postgres:15.1
    ports:
      - "5001:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRE_DB=postgres
